game_set_speed(60, 60);
image_xscale = 4; // Scale width to 2x
image_yscale = 4; // Scale height to 2x
meleeBaseDamage = [2, 10, 5, 2, 20, 25, 9, 1, 1];
//ype = {"Regular", "Shit", "Juggernaut", "Fast", "Scout", "Heavy", "Robot", "Worker", "Spiderfilth"};
meleeCooldownTimes = [1.5, 3, 3, 0.4, 1.5, 2, 1.4, 0.7]
meleeExp = [10, 10, 10, 10, 10, 10, 10, 10, 10];

//Gun, Shotgun, Pyro, Demo
rangedCooldownTimes = [1.5, 1.5, 0.1, 2]
ranges = [10, 3, 3, 5];
rangedBaseDamage = [1, 2, 4, 5]
lastBucket = 0
lastthingy = 0
last_action_time = 0;
global.last_action_time = 0;
is_poisoned = false;
is_burning = false;
global.time = 1;
global.revive = [160,160]
poison_hits = 0;
burning_hits = 0;
poison_last_time = 0;
burning_last_time = 0;
move_speed = 4;         
max_speed = 8;                   
stamina_drain_rate = 1;      
stamina_regen_rate = 0.5;    
h_speed = 0;            
v_speed = 0;               
sprinting = false;          
baseHealth = 100/(1+global.i);
baseStamina = 100;
baseDamage = 3;
blood = 0;
armour = 1;
level = 1;
experience = 0;
damage = baseDamage;
Playerhealth = baseHealth;
stamina = baseStamina;
max_stamina = baseStamina;
cooldown_time = 1;
experience = 0;
previous = 0
range = 100;
knockback = range;
knockback_decay = 0.9;
killsSinceDrop = 0;
dropCooldown = 3;
past = 0
wet = false;
last_splash=0;
last_shot = 0;
bucket_cooldown = 10;
line_start_x = 0;
line_start_y = 0;
line_end_x = 0;
line_end_y = 0;
line_start_time = -1; // -1 indicates no line is being drawn

Enemies = [oFinalBoss, oDemonRegular, oDemonFast, oDemonJuggernaut, oDemonRobot, oDemonWorker, oSpiderFilth, oDemonGun, oDemonDemo, oDemonPyro, oDemonShotgun, oDemonScout, oSummoner, oShitDemon, oShitToilet, oTrap];

//items
lysol = true;
bucket = true;
ammo = 0;
keys = 0;
i = 1
global.times = 0;